"""empty message

Revision ID: 27205487fccc
Revises: 59ceddc838a8
Create Date: 2017-11-01 15:57:36.180336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27205487fccc'
down_revision = '59ceddc838a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('name', sa.String(length=64), nullable=True))
    #op.drop_column('inspections', 'description')
    #op.drop_column('inspections', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('item', sa.TEXT(), nullable=True))
    op.add_column('inspections', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('inspections', 'name')
    op.drop_column('inspections', 'inspection')
    # ### end Alembic commands ###
