"""empty message

Revision ID: 59ceddc838a8
Revises: 0ec713d6843f
Create Date: 2017-11-01 12:31:02.213564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ceddc838a8'
down_revision = '0ec713d6843f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sub_id')
    # ### end Alembic commands ###
