"""empty message

Revision ID: 72c38df602f4
Revises: dd94fcaff74b
Create Date: 2017-11-03 11:35:18.035744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c38df602f4'
down_revision = 'dd94fcaff74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('contractor', sa.VARCHAR(length=64), nullable=True),
    sa.Column('inspection', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['contractor'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['inspection'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
