"""empty message

Revision ID: 7d307e55f3f3
Revises: 72c38df602f4
Create Date: 2017-11-03 11:35:34.782440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d307e55f3f3'
down_revision = '72c38df602f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignedcontractors',
    sa.Column('left_id', sa.String(length=64), nullable=False),
    sa.Column('right_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['assigned.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('assignedinspections',
    sa.Column('left_id', sa.String(length=64), nullable=False),
    sa.Column('right_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['assigned.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('assignedsites',
    sa.Column('left_id', sa.String(length=64), nullable=False),
    sa.Column('right_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['assigned.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignedsites')
    op.drop_table('assignedinspections')
    op.drop_table('assignedcontractors')
    op.drop_table('assigned')
    # ### end Alembic commands ###
