"""empty message

Revision ID: dd94fcaff74b
Revises: 59ceddc838a8
Create Date: 2017-11-03 09:40:53.875342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd94fcaff74b'
down_revision = '59ceddc838a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'zipcode')
    op.drop_column('contractors', 'zipcode')
    # ### end Alembic commands ###
